# Generated by Django 3.1.4 on 2021-01-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
